pipeline {
    agent { label 'master' }
     environment {                 

        //Job Upload
        Project_Name = "Sterling"  //Sterling/ControlCenter
        Pattern = "*.tar"       //duplicado
        SourceFiles = "*.tar"   //duplicado
        PgmPattern = "*.xml"
        Accion = "zFile"
        Tipo = "Compress"

        //Variables Dinamicas
        //Información  Repo
        UriGit = "$GIT_URL"
        UserIDGit = "UserBitbucketSterling"
        
        //Revisar como sacar del git
        ComBrachGit = "$GIT_BRANCH"  //develop/release/master //Revisar como sacar del git
        ComTempWork = "$WORKSPACE"  //develop/release/master //Revisar como sacar del git

        //Variables File storage
        RemoteDirectory = "${RemoteDirectory}"
        PathFolderVars = "${PgmSh}/${FolderVars}"

        }
        stages {
        stage ('Variables') {
                steps {
                    script
                        {
                        //extrae nombre JOb
                        env.TempWorkSpacePru1 = ComTempWork.substring(ComTempWork.lastIndexOf('/')+1)
                        sh 'echo "nombreJob: $TempWorkSpacePru1"'

                        env.BrachGit = ComBrachGit.substring(ComBrachGit.indexOf('/')+1)
                        sh 'echo "BrachGit: $BrachGit"'

                        //extrae directamente opcion2
                        env.TempWorkSpaceOK = ComTempWork.substring(0,ComTempWork.lastIndexOf('Job_Master_Repo_Sfg_Proc_00056'))
                        sh 'echo "TemWorkspaceOK: $TempWorkSpaceOK"'

                        //Complemtanta Job por variable
                        env.TempWorkSpace = ComTempWork.substring(0,ComTempWork.lastIndexOf("${TempWorkSpacePru1}"))
                        sh 'echo "RutaTempWork: $TempWorkSpace"'

                        env.TmpWokJobBuildRepos = "${TempWorkSpace}/Job_Build_Repos"
                        sh 'echo "TmpWokJobBuildRepos: $TmpWokJobBuildRepos"'
                        
                        env.TmpWokJobJfrogUpload = "${TempWorkSpace}/Job_Jfrog_Upload"
                        sh 'echo "TmpWokJobJfrogUpload: $TmpWokJobJfrogUpload"'

                        env.TmpWokJobJfrogDownload = "${TempWorkSpace}/Job_Jfrog_Download"
                        sh 'echo "TmpWokJobJfrogDownload: $TmpWokJobJfrogDownload"'

                        env.TypeEnvironment= "${env.BrachGit}" //Develop/Release/Production //Revisar como sacar del git
                        sh 'echo "TypeEnvironment: $TypeEnvironment"'   

                        env.TypeEnvironmentSSH = "${env.BrachGit}" //Develop/UAT/PRDN1/PRDN1 //Revisar como sacar del git
                        sh 'echo "TypeEnvironmentSSH: $TypeEnvironmentSSH"'   
                        
                        env.Job_Copy = "Job_SSH_Copy_${env.TypeEnvironmentSSH}"
                        sh 'echo "Job_Copy: $Job_Copy"'   

                        env.TmpWorkJobCopyWorkspace = "${TempWorkSpace}/${env.Job_Copy}"
                        sh 'echo "TmpWorkJobCopyWorkspace: $TmpWorkJobCopyWorkspace"'
                                                
                    }                            
                } 
        }      
        stage('Job Build Repos') {
        steps {
                script {
                        build job: "Job_Build_Repos", parameters: [
                                string(name: 'AntUriGit', value: "$UriGit"),
                                string(name: 'AntUserIDGit', value: "$UserIDGit"),
                                string(name: 'AntBrachGit', value: "$env.BrachGit"),
                                string(name: 'AntPgmPattern', value: "$PgmPattern"),
                                string(name: 'AntAccion', value: "$Accion"),
                                string(name: 'AntTmpWokJobMasterRepos', value: "$TmpWokJobBuildRepos"),
                                string(name: 'AntTipo', value: "$Tipo")
                                ]                                
                                //Parameters Upload
                                env.FileTar = sh (script: 'cat $WORKSPACE/$PathFolderVars/$VarName', returnStdout: true).trim()
                                env.FileBuild = FileTar.substring(0,FileTar.indexOf('.'))
                        }
                }
                post {
                success {                                
                                //Completo Satisfactoriamente
                                echo "Sub Job Build Repos: ${env.BrachGit} Sucessfully"
                        }
                failure {
                                //Fallo Job revisar Ejecución en el Job Interno
                                echo "Failed Job Build Repos"
                                }
                        }
        
                }
        stage('Job Jfrog Upload') {
        steps {
                script {
                        build job: "Job_Jfrog_Upload", parameters: [
                                string(name: 'AntTempWorkspace', value: "$TmpWokJobBuildRepos"),
                                string(name: 'AntFileTar', value: "$FileTar"),
                                string(name: 'AntProject_Name', value: "$Project_Name"),
                                string(name: 'AntTypeEnvironment', value: "$TypeEnvironment"),
                                string(name: 'AntPattern', value: "$Pattern")
                                ]
                        }
                }
                post {
                success {
                                //Completo Satisfactoriamente
                                echo "Sub Job Jfrog Upload: ${FileTar} Sucessfully"

                        }
                failure {
                                //Fallo Job revisar Ejecución en el Job Interno
                                echo "Failed Sub Job Jfrog Upload"
                        }
                }
        }
        stage('Job Jfrog Download') {
        steps {
                script  {
                        build job: "Job_Jfrog_Download", parameters: [
                                string(name: 'AntFileBuild', value: "$FileBuild"),
                                string(name: 'AntTempWorkspace', value: "$TmpWokJobBuildRepos"),
                                string(name: 'AntFileTar', value: "$FileTar"),
                                string(name: 'AntProject_Name', value: "$Project_Name"),
                                string(name: 'AntTypeEnvironment', value: "$TypeEnvironment"),
                                string(name: 'AntSourceFiles', value: "$SourceFiles"),
                                string(name: 'AntRemoteDirectory', value: "$RemoteDirectory"),
                                string(name: 'AntJob_Copy', value: "$Job_Copy"),
                                string(name: 'AntTmpWorkJobCopyWorkspace', value: "${TmpWorkJobCopyWorkspace}"),
                                string(name: 'AntTypeEnvironmentSSH', value: "$TypeEnvironmentSSH")
                                ]
                        }
                }
                post {
                success {
                                //Completo Satisfactoriamente
                                echo "Sub Job Jfrog Download: ${FileBuild} Sucessfully"
                        }
                failure {
                                //Fallo Job revisar Ejecución en el Job Interno
                                echo "Failed Sub Job Jfrog Download"
                        }
                }
        }
        stage("Job Copy Artifacts SSH") {
                steps {
                        build job: "Job_SSH_Copy_${TypeEnvironmentSSH}", parameters: [
                        string(name: 'AntSourceFiles', value: "${SourceFiles}"),
                        string(name: 'AntRemoteDirectory', value: "${RemoteDirectory}")
                        ]
                }
                post {
                        success {
                                        //Completo Satisfactoriamente
                                        echo "Sub Job Copy Artifacts SSH: ${RemoteDirectory} Sucessfully"
                                 }
                        failure {
                                        //Fallo Job revisar Ejecución en el Job Interno
                                        echo "Failed Sub Job Copy Artifacts SSH"
                        }
                }
        }
        stage("Job SSH Deploy Sterling") {
                steps {
                        build job: "Job_SSH_Deploy" , wait: true
                }
                post {
                        success {
                                        //Completo Satisfactoriamente
                                        echo "Sub Job SSH Deploy Sterling: Sucessfully"
                                 }
                        failure {
                                        //Fallo Job revisar Ejecución en el Job Interno
                                        sh 'rm -rf ${TmpWorkJobCopyWorkspace}/*'
                                        echo "Failed Sub Job SSH Deploy Sterling"
                        }
                }
        }
        stage ('Removing files') {
                steps {
                    script
                        { 
                            //Clean WORKSPACE Job
                            sh 'rm -rf $WORKSPACE/*'
                            sh 'rm -rf ${TmpWorkJobCopyWorkspace}*'
                    }                            
                }
                post {
                    success {
                                //Completo Satisfactoriamente
                                echo "Cleanup Enviroment  Sucessfully"
                            }
                    failure {
                                //Fallo Job revisar Ejecución en el Job Interno
                                echo "Failed Cleanup Enviroment "
                        }
                }
        }
    
    }
}